BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "VoteLists" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"VoteList_ID"	INTEGER NOT NULL,
	"User_ID"	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "Election" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Song_ID"	INTEGER NOT NULL UNIQUE,
	"VoteList_ID"	INTEGER NOT NULL,
	FOREIGN KEY("Song_ID") REFERENCES "Songs"("ID")
);
CREATE TABLE IF NOT EXISTS "User" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Username"	TEXT NOT NULL UNIQUE,
	"Password"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "Songs" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Artist"	TEXT,
	"Album"	TEXT,
	"Title"	TEXT NOT NULL,
	"Genre"	TEXT,
	"Path"	TEXT NOT NULL UNIQUE
);
INSERT INTO "User" VALUES (0,'admin','admin');
INSERT INTO "User" VALUES (1,'user','password');
COMMIT;
